name       : font-tlwg-ttf
version    : 0.6.5
release    : 2
source     :
    - https://github.com/tlwg/fonts-tlwg/releases/download/v0.6.5/ttf-tlwg-0.6.5.tar.xz : 1541187a0c785eae4c00d61c9edef2fcaf3164af18add3f8045f8bb20d628036
license    :
    - GPL-2.0
    - MIT # Waree
component  : desktop.font
summary    : Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
description: |
    Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
install    : |
    install -d $installdir/usr/share/fonts/truetype/thai
    cp *.ttf $installdir/usr/share/fonts/truetype/thai
    mv fontconfig/conf.avail $installdir/usr/share/fonts/conf.d
    chmod 00644 -R $installdir/usr/share/fonts
