name       : font-tlwg-ttf
version    : 0.6.3
release    : 1
source     :
    - https://github.com/tlwg/fonts-tlwg/archive/v0.6.3.tar.gz : 082b7ac13933e52089ec79a571cfe333021a846969cbdd3a4125c44fad66de02
license    :
    - GPL-2.0
    - MIT # Waree
component  : desktop.font
summary    : Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
description: |
    Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
builddeps  :
    - fontforge
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/fonts/conf.avail $installdir/usr/share/fonts/conf.d
    rm -rf $installdir/etc
