name       : font-tlwg-ttf
version    : 0.7.1
release    : 3
source     :
    - https://github.com/tlwg/fonts-tlwg/releases/download/v0.7.1/ttf-tlwg-0.7.1.tar.xz : cfae0305b1a78a0dfc780d37586b42709a41d14b5aab5e3e84e2746995f457a2
license    :
    - GPL-2.0-only
    - MIT # Waree
component  : desktop.font
summary    : Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
description: |
    Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
install    : |
    install -d $installdir/usr/share/fonts/truetype/thai
    cp *.ttf $installdir/usr/share/fonts/truetype/thai
    mv fontconfig/conf.avail $installdir/usr/share/fonts/conf.d
    chmod 00644 -R $installdir/usr/share/fonts
